//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.IoTSuite.Connectedfactory.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.IoTSuite.Connectedfactory.WebApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of products above maximum.
        /// </summary>
        internal static string AlertKpi1AboveMaximum {
            get {
                return ResourceManager.GetString("AlertKpi1AboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of products below minimum.
        /// </summary>
        internal static string AlertKpi1BelowMinimum {
            get {
                return ResourceManager.GetString("AlertKpi1BelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy consumption above maximum.
        /// </summary>
        internal static string AlertKpi2AboveMaximum {
            get {
                return ResourceManager.GetString("AlertKpi2AboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy consumption below minimum.
        /// </summary>
        internal static string AlertKpi2BelowMinimum {
            get {
                return ResourceManager.GetString("AlertKpi2BelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Availability above maximum.
        /// </summary>
        internal static string AlertOeeAvailabilityAboveMaximum {
            get {
                return ResourceManager.GetString("AlertOeeAvailabilityAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Availability below minimum.
        /// </summary>
        internal static string AlertOeeAvailabilityBelowMinimum {
            get {
                return ResourceManager.GetString("AlertOeeAvailabilityBelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Overall above maximum.
        /// </summary>
        internal static string AlertOeeOverallAboveMaximum {
            get {
                return ResourceManager.GetString("AlertOeeOverallAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Overall below minimum.
        /// </summary>
        internal static string AlertOeeOverallBelowMinimum {
            get {
                return ResourceManager.GetString("AlertOeeOverallBelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Performance above maximum.
        /// </summary>
        internal static string AlertOeePerformanceAboveMaximum {
            get {
                return ResourceManager.GetString("AlertOeePerformanceAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Performance below minimum.
        /// </summary>
        internal static string AlertOeePerformanceBelowMinimum {
            get {
                return ResourceManager.GetString("AlertOeePerformanceBelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Quality above maximum.
        /// </summary>
        internal static string AlertOeeQualityAboveMaximum {
            get {
                return ResourceManager.GetString("AlertOeeQualityAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Qualty below minimum.
        /// </summary>
        internal static string AlertOeeQualityBelowMinimum {
            get {
                return ResourceManager.GetString("AlertOeeQualityBelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor value above maximum.
        /// </summary>
        internal static string AlertValueAboveMaximum {
            get {
                return ResourceManager.GetString("AlertValueAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor value below minimum.
        /// </summary>
        internal static string AlertValueBelowMinimum {
            get {
                return ResourceManager.GetString("AlertValueBelowMinimum", resourceCulture);
            }
        }
    }
}
